[package]
name = "cvtree"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsing = { git = "https://github.com/hehaowen00/parsing" }
libc = "0.2.101"
